# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('contenido', models.TextField()),
                ('tipo', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Cerrado'), (1, 'Activo')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actividades', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
